version: "3.8"

services:
  yggdrasil:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yggdrasil-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    command: npm run dev
    restart: unless-stopped
